version: '2.4'
services:
  tvtimeplex:
    container_name: tvtimeplex
    build:
      context: .
    image: "bigorno/plex-tvtime-webhook:latest"
    restart: unless-stopped
    ports:
      - "10000:10000"
    volumes:
      - ./conf:/opt/plex-tvtime-webhook/conf
    entrypoint: /usr/local/bin/entrypoint.sh