version: '2'
services:
  tvtimeplex:
    container_name: tvtimeplex
    build:
      context: .
    image: "bigorno/plex-tvtime-webhook:latest"
    restart: unless-stopped
    volumes:
      - ./conf:/opt/plex-tvtime-webhook/conf